-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgYSAa3gettmdKJqlX
epGQJTwNNlzEK/F1SxppuAdIETigCgYIKoZIzj0DAQehRANCAAT/IjqbIFxkHwN2
5eGAgmaaz2Z5PVxcnhoMdnllzDd5hjaVElxMMf5NynAIjXNtxj4f5mm0wVtFI0lG
RZTstAmV
-----END PRIVATE KEY-----