import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:untitled/generated/locale_keys.g.dart';

import 'nationality_list.dart';

var countryList = <String>[
  "Абхазия",
  "Австралия",
  "Австрия",
  "Азербайджан",
  "Албания",
  "Алжир",
  "Американское Самоа",
  "Ангилья",
  "Ангола",
  "Андорра",
  "Антарктида",
  "Антигуа и Барбуда",
  "Аргентина",
  "Армения",
  "Аруба",
  "Афганистан",
  "Багамы",
  "Бангладеш",
  "Барбадос",
  "Бахрейн",
  "Беларусь",
  "Белиз",
  "Бельгия",
  "Бенин",
  "Бермуды",
  "Болгария",
  "Боливия, Многонациональное Государство",
  "Бонайре, Саба и Синт-Эстатиус",
  "Босния и Герцеговина",
  "Ботсвана",
  "Бразилия",
  "Британская территория в Индийском океане",
  "Бруней-Даруссалам",
  "Буркина-Фасо",
  "Бурунди",
  "Бутан",
  "Вануату",
  "Венгрия",
  "Венесуэла Боливарианская Республика",
  "Виргинские острова, Британские",
  "Виргинские острова, США",
  "Вьетнам",
  "Габон",
  "Гаити",
  "Гайана",
  "Гамбия",
  "Гана",
  "Гваделупа",
  "Гватемала",
  "Гвинея",
  "Гвинея-Бисау",
  "Германия",
  "Гернси",
  "Гибралтар",
  "Гондурас",
  "Гонконг",
  "Гренада",
  "Гренландия",
  "Греция",
  "Грузия",
  "Гуам",
  "Дания",
  "Джерси",
  "Джибути",
  "Доминика",
  "Доминиканская Республика",
  "Египет",
  "Замбия",
  "Западная Сахара",
  "Зимбабве",
  "Израиль",
  "Индия",
  "Индонезия",
  "Иордания",
  "Ирак",
  "Иран, Исламская Республика",
  "Ирландия",
  "Исландия",
  "Испания",
  "Италия",
  "Йемен",
  "Кабо-Верде",
  "Казахстан",
  "Камбоджа",
  "Камерун",
  "Канада",
  "Катар",
  "Кения",
  "Кипр",
  "Киргизия",
  "Кирибати",
  "Китай",
  "Кокосовые (Килинг) острова",
  "Колумбия",
  "Коморы",
  "Конго",
  "Конго, Демократическая Республика",
  "Корея, Народно-Демократическая Республика",
  "Корея, Республика",
  "Коста-Рика",
  "Кот д'Ивуар",
  "Куба",
  "Кувейт",
  "Кюрасао",
  "Лаос",
  "Латвия",
  "Лесото",
  "Ливан",
  "Ливийская Арабская Джамахирия",
  "Либерия",
  "Лихтенштейн",
  "Литва",
  "Люксембург",
  "Маврикий",
  "Мавритания",
  "Мадагаскар",
  "Майотта",
  "Макао",
  "Малави",
  "Малайзия",
  "Мали",
  "Малые Тихоокеанские отдаленные острова Соединенных Штатов",
  "Мальдивы",
  "Мальта",
  "Марокко",
  "Мартиника",
  "Маршалловы острова",
  "Мексика",
  "Микронезия, Федеративные Штаты",
  "Мозамбик",
  "Молдова, Республика",
  "Монако",
  "Монголия",
  "Монтсеррат",
  "Мьянма",
  "Намибия",
  "Науру",
  "Непал",
  "Нигер",
  "Нигерия",
  "Нидерланды",
  "Никарагуа",
  "Ниуэ",
  "Новая Зеландия",
  "Новая Каледония",
  "Норвегия",
  "Объединенные Арабские Эмираты",
  "Оман",
  "Остров Буве",
  "Остров Мэн",
  "Остров Норфолк",
  "Остров Рождества",
  "Остров Херд и острова Макдональд",
  "Острова Кайман",
  "Острова Кука",
  "Острова Теркс и Кайкос",
  "Пакистан",
  "Палау",
  "Палестинская территория, оккупированная",
  "Панама",
  "Папский Престол (Государство — город Ватикан)",
  "Папуа-Новая Гвинея",
  "Парагвай",
  "Перу",
  "Питкерн",
  "Польша",
  "Португалия",
  "Пуэрто-Рико",
  "Республика Македония",
  "Реюньон",
  "Россия",
  "Руанда",
  "Румыния",
  "Самоа",
  "Сан-Марино",
  "Сан-Томе и Принсипи",
  "Саудовская Аравия",
  "Святая Елена, Остров вознесения, Тристан-да-Кунья",
  "Северные Марианские острова",
  "Сен-Бартельми",
  "Сен-Мартен",
  "Сенегал",
  "Сент-Винсент и Гренадины",
  "Сент-Китс и Невис",
  "Сент-Люсия",
  "Сент-Пьер и Микелон",
  "Сербия",
  "Сейшелы",
  "Сингапур",
  "Синт-Мартен",
  "Сирийская Арабская Республика",
  "Словакия",
  "Словения",
  "Соединенное Королевство",
  "Соединенные Штаты Америки, США",
  "Соломоновы острова",
  "Сомали",
  "Судан",
  "Суринам",
  "Сьерра-Леоне",
  "Таджикистан",
  "Таиланд",
  "Тайвань (Китай)",
  "Танзания, Объединенная Республика",
  "Тимор-Лесте",
  "Того",
  "Токелау",
  "Тонга",
  "Тринидад и Тобаго",
  "Тувалу",
  "Тунис",
  "Туркмения",
  "Турция",
  "Уганда",
  "Узбекистан",
  "Украина",
  "Уоллис и Футуна",
  "Уругвай",
  "Фарерские острова",
  "Фиджи",
  "Филиппины",
  "Финляндия",
  "Фолклендские острова (Мальвинские)",
  "Франция",
  "Французская Гвиана",
  "Французская Полинезия",
  "Французские Южные территории",
  "Хорватия",
  "Центрально-Африканская Республика",
  "Чад",
  "Черногория",
  "Чешская Республика",
  "Чили",
  "Швейцария",
  "Швеция",
  "Шпицберген и Ян-Майен",
  "Шри-Ланка",
  "Эквадор",
  "Экваториальная Гвинея",
  "Эландские острова",
  "Эль-Сальвадор",
  "Эритрея",
  "Эсватини",
  "Эстония",
  "Эфиопия",
  "Южная Африка",
  "Южная Джорджия и Южные Сандвичевы острова",
  "Южная Осетия",
  "Южный Судан",
  "Ямайка",
  "Япония",
];

var countryListEn = <String>[
  "Abkhazia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Anguilla",
  "Angola",
  "Andorra",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Afghanistan",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Bahrain",
  "Belarus",
  "Belize",
  "Belgium",
  "Benin",
  "Bermuda",
  "Bulgaria",
  "Bolivia, plurinational state of",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Burkina Faso",
  "Burundi",
  "Bhutan",
  "Vanuatu",
  "Hungary",
  "Venezuela",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Vietnam",
  "Gabon",
  "Haiti",
  "Guyana",
  "Gambia",
  "Ghana",
  "Guadeloupe",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Germany",
  "Guernsey",
  "Gibraltar",
  "Honduras",
  "Hong Kong",
  "Grenada",
  "Greenland",
  "Greece",
  "Georgia",
  "Guam",
  "Denmark",
  "Jersey",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Egypt",
  "Zambia",
  "Western Sahara",
  "Zimbabwe",
  "Israel",
  "India",
  "Indonesia",
  "Jordan",
  "Iraq",
  "Iran, Islamic Republic of",
  "Ireland",
  "Iceland",
  "Spain",
  "Italy",
  "Yemen",
  "Cape Verde",
  "Kazakhstan",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Qatar",
  "Kenya",
  "Cyprus",
  "Kyrgyzstan",
  "Kiribati",
  "China",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, Democratic Republic",
  "Korea",
  "Korea, Democratic People's republic of Korea",
  "Costa Rica",
  "Cote d'Ivoire",
  "Cuba",
  "Kuwait",
  "Curaçao",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lesotho",
  "Lebanon",
  "Libyan Arab Jamahiriya",
  "Liberia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Mauritius",
  "Mauritania",
  "Madagascar",
  "Mayotte",
  "Macao",
  "Malawi",
  "Malaysia",
  "Mali",
  "United States Minor Outlying Islands",
  "Maldives",
  "Malta",
  "Morocco",
  "Martinique",
  "Marshall Islands",
  "Mexico",
  "Micronesia, Federated States of",
  "Mozambique",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montserrat",
  "Burma",
  "Namibia",
  "Nauru",
  "Nepal",
  "Niger",
  "Nigeria",
  "Netherlands",
  "Nicaragua",
  "Niue",
  "New Zealand",
  "New Caledonia",
  "Norway",
  "United Arab Emirates",
  "Oman",
  "Bouvet Island",
  "Isle of Man",
  "Norfolk Island",
  "Christmas Island",
  "Heard Island and McDonald Islands",
  "Cayman Islands",
  "Cook Islands",
  "Turks and Caicos Islands",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Holy See (Vatican City State)",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Macedonia, The Former Yugoslav Republic Of",
  "Reunion",
  "Russian Federation",
  "Rwanda",
  "Romania",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Saint Helena, Ascension And Tristan Da Cunha",
  "Northern Mariana Islands",
  "Saint Barthélemy",
  "Saint Martin (French Part)",
  "Senegal",
  "Saint Vincent and the Grenadines",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Serbia",
  "Seychelles",
  "Singapore",
  "Sint Maarten",
  "Syrian Arab Republic",
  "Slovakia",
  "Slovenia",
  "United Kingdom",
  "United States",
  "Solomon Islands",
  "Somalia",
  "Sudan",
  "Suriname",
  "Sierra Leone",
  "Tajikistan",
  "Thailand",
  "Taiwan, Province of China",
  "Tanzania, United Republic Of",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tuvalu",
  "Tunisia",
  "Turkmenistan",
  "Turkey",
  "Uganda",
  "Uzbekistan",
  "Ukraine",
  "Wallis and Futuna",
  "Uruguay",
  "Faroe Islands",
  "Fiji",
  "Philippines",
  "Finland",
  "Falkland Islands (Malvinas)",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Croatia",
  "Central African Republic",
  "Chad",
  "Montenegro",
  "Czech Republic",
  "Chile",
  "Switzerland",
  "Sweden",
  "Svalbard and Jan Mayen",
  "Sri Lanka",
  "Ecuador",
  "Equatorial Guinea",
  "Åland Islands",
  "El Salvador",
  "Eritrea",
  "Eswatini",
  "Estonia",
  "Ethiopia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Ossetia",
  "South Sudan",
  "Jamaica",
  "Japan",
];

Map<String, String> educationList = {
  "basicGeneral": LocaleKeys.educationList_basicGeneral,
  "secondaryGeneral": LocaleKeys.educationList_secondaryGeneral,
  "secondaryVocational": LocaleKeys.educationList_secondaryVocational,
  "higherBachelorOrSpecialist":
      LocaleKeys.educationList_higherBachelorOrSpecialist,
  "higherMaster": LocaleKeys.educationList_higherMaster,
  "academicDegree": LocaleKeys.educationList_academicDegree,
};

Map<String, String> familyState = {
  "notMarried": LocaleKeys.familyState_notMarried,
  "married": LocaleKeys.familyState_married,
  "divorced": LocaleKeys.familyState_divorced
};

Map<String, String> faithState = {
  "observantMuslim": LocaleKeys.faithState_observantMuslim,
  "nonObservantMuslim": LocaleKeys.faithState_nonObservantMuslim,
  "notSelected": LocaleKeys.faithState_notSelected,
};

Map<String, String> observantOfTheCanonsMaleState = {
  "observingIslamCanons":
      LocaleKeys.observantOfTheCanonsMaleState_observingIslamCanons,
  "nonObservingIslamCanons":
      LocaleKeys.observantOfTheCanonsMaleState_nonObservingIslamCanons,
};

Map<String, String> observantOfTheCanonsFemaleState = {
  "observingIslamCanons":
      LocaleKeys.observantOfTheCanonsFemaleState_observingIslamCanons,
  "nonObservingIslamCanons":
      LocaleKeys.observantOfTheCanonsFemaleState_nonObservingIslamCanons,
};

var childrenState = <String>[
  LocaleKeys.childrenState_yes.tr(),
  LocaleKeys.childrenState_no.tr(),
];

Map<bool, String> chldrnState = {
  true: LocaleKeys.childrenState_yes,
  false: LocaleKeys.childrenState_no
};

Map<String, String> addictionList = {
  'smoking': LocaleKeys.badHabbits_smoking,
  'alcohol': LocaleKeys.badHabbits_alcohol,
  'gambling': LocaleKeys.badHabbits_gambling,
  'other': LocaleKeys.badHabbits_other_h,
};

class GlobalStrings {
  static String translateNationalityFromRu(
      BuildContext context, String? nationality) {
    if (nationality == null) {
      return "";
    }

    var result = "";

    if (context.locale.languageCode == "ru") {
      return nationality;
    } else {
      for (int i = 0; i < nationalityList.length; ++i) {
        if (nationalityList[i].toLowerCase() == nationality.toLowerCase()) {
          if (nationalityListEn.length > i) {
            result = nationalityListEn[i];
          } else {
            result = "";
          }
          break;
        }
      }
    }

    return result;
  }

  static List<Map<String, String>> getBadHabits() {
    return [
      {
        'label': LocaleKeys.badHabbits_smoking.tr(),
        'value': 'smoking',
      },
      {
        'label': LocaleKeys.badHabbits_alcohol.tr(),
        'value': 'alcohol',
      },
      {
        'label': LocaleKeys.badHabbits_gambling.tr(),
        'value': 'gambling',
      },
      {
        'label': LocaleKeys.badHabbits_other_h.tr(),
        'value': 'other',
      },
    ];
  }
}

// List<Map<String, String>> badHabbits = [
//     {
//         'label': LocaleKeys.badHabbits_smoking.tr(),
//         'value': 'smoking',
//     },
//     {
//         'label': LocaleKeys.badHabbits_alcohol.tr(),
//         'value': 'alcohol',
//     },
//     {
//         'label': LocaleKeys.badHabbits_gambling.tr(),
//         'value': 'gambling',
//     },
//     {
//         'label': LocaleKeys.badHabbits_other_h.tr(),
//         'value': 'other',
//     },
// ];

class interestTag {
  interestTag(this.str, this.clr);
  String str = "";
  Color clr = Colors.green;
}

List<Color> tagsColors = <Color>[
  const Color.fromARGB(255, 250, 190, 215),
  const Color.fromARGB(255, 194, 225, 221),
  const Color.fromARGB(255, 196, 218, 243),
  const Color.fromARGB(255, 255, 225, 191),
  const Color.fromARGB(255, 217, 205, 233),
  const Color.fromARGB(255, 227, 208, 215),
  const Color.fromARGB(255, 214, 239, 197),
];

var interestList = <interestTag>[
  interestTag(
      LocaleKeys.interestTag_walks, const Color.fromARGB(255, 250, 190, 215)),
  interestTag(
      LocaleKeys.interestTag_sport, const Color.fromARGB(255, 194, 225, 221)),
  interestTag(
      LocaleKeys.interestTag_cinema, const Color.fromARGB(255, 196, 218, 243)),
  interestTag(
      LocaleKeys.interestTag_yoga, const Color.fromARGB(255, 255, 225, 191)),
  interestTag(
      LocaleKeys.interestTag_food, const Color.fromARGB(255, 217, 205, 233)),
  interestTag(
      LocaleKeys.interestTag_tourism, const Color.fromARGB(255, 227, 208, 215)),
  interestTag(
      LocaleKeys.interestTag_leisure, const Color.fromARGB(255, 214, 239, 197)),
  interestTag(LocaleKeys.interestTag_swimming,
      const Color.fromARGB(255, 196, 218, 243)),
  interestTag(LocaleKeys.interestTag_crossFit,
      const Color.fromARGB(255, 194, 225, 221)),
  interestTag(
      LocaleKeys.interestTag_bicycle, const Color.fromARGB(255, 217, 205, 233)),
  interestTag(
      LocaleKeys.interestTag_animals, const Color.fromARGB(255, 227, 208, 215)),
  interestTag(
      LocaleKeys.interestTag_comedy, const Color.fromARGB(255, 255, 225, 191)),
  interestTag(
      LocaleKeys.interestTag_love, const Color.fromARGB(255, 250, 190, 215)),
];

Map<String, String> standartInterestList = {
  "Walks": "Прогулки",
  "Sport": "Спорт",
  "Cinema": "Кино",
  "Yoga": "Йога",
  "Food": "Еда",
  "Tourism": "Туризм",
  "Leisure": "Активный отдых",
  "Swimming": "Бассейн",
  "CrossFit": "Кроссфит",
  "Bicycle": "Велосипед",
  "Animals": "Животные",
  "Comedy": "Комедия",
  "Love": "Любовь"
};
